Repository knaxus/rest-and-graphql, pull requests merged in 2019-10, with the labels that each got.

#5 Update dependencies
  package-lock.json
  package.json
Labels: beginner friendly, enhancement, good first issue, hacktoberfest

#8 Issue 6
  src/graphql/resolvers/index.js
  src/graphql/typedefs/index.js
  src/services/products/index.js
  src/services/reviews/index.js
  src/services/sellers/index.js
  src/services/users/index.js
Labels: beginner friendly, enhancement, hacktoberfest

#9 Feat: Issue-7
  src/graphql/resolvers/index.js
  src/graphql/typedefs/index.js
Labels: hacktoberfest
